#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyopencl
Version  : 2017.1.1
Release  : 4
URL      : https://github.com/pyopencl/pyopencl/archive/v2017.1.1.tar.gz
Source0  : https://github.com/pyopencl/pyopencl/archive/v2017.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: pyopencl-python
BuildRequires : Mako
BuildRequires : beignet-dev
BuildRequires : cffi
BuildRequires : numpy
BuildRequires : ocl-icd-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycparser
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Experimental Fortran-to-OpenCL translator
-----------------------------------------

%package python
Summary: python components for the pyopencl package.
Group: Default

%description python
python components for the pyopencl package.


%prep
%setup -q -n pyopencl-2017.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1496439430
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1496439430
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
