#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyopencl
Version  : 2016.2.1
Release  : 1
URL      : https://github.com/pyopencl/pyopencl/archive/v2016.2.1.tar.gz
Source0  : https://github.com/pyopencl/pyopencl/archive/v2016.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: pyopencl-python
BuildRequires : Mako
BuildRequires : beignet-dev
BuildRequires : cffi
BuildRequires : numpy
BuildRequires : ocl-icd-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycparser
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Experimental Fortran-to-OpenCL translator
-----------------------------------------

%package python
Summary: python components for the pyopencl package.
Group: Default

%description python
python components for the pyopencl package.


%prep
%setup -q -n pyopencl-2016.2.1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
